"""add file text

Revision ID: a38a713ed79e
Revises: 49c0404cd10b
Create Date: 2024-06-22 17:37:36.945857

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "a38a713ed79e"
down_revision: Union[str, None] = "49c0404cd10b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_text",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("file_text", sa.Text(), nullable=True),
        sa.Column(
            "search_vector",
            sqlalchemy_utils.types.ts_vector.TSVectorType(),
            nullable=True,
        ),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("last_modified_on", sa.DateTime(), nullable=True),
        sa.Column("deleted_on", sa.DateTime(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_file_search_vector",
        "file_text",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_file_text_file_id"), "file_text", ["file_id"], unique=True)
    op.create_index(op.f("ix_file_text_id"), "file_text", ["id"], unique=False)
    op.add_column("files", sa.Column("file_text_id", sa.UUID(), nullable=False))
    op.create_unique_constraint(None, "files", ["file_text_id"])
    op.create_foreign_key(None, "files", "file_text", ["file_text_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "files", type_="foreignkey")
    op.drop_constraint(None, "files", type_="unique")
    op.drop_column("files", "file_text_id")
    op.drop_index(op.f("ix_file_text_id"), table_name="file_text")
    op.drop_index(op.f("ix_file_text_file_id"), table_name="file_text")
    op.drop_index(
        "ix_file_search_vector", table_name="file_text", postgresql_using="gin"
    )
    op.drop_table("file_text")
    # ### end Alembic commands ###
