"""fix

Revision ID: 37ffb990dd9d
Revises: a38a713ed79e
Create Date: 2024-06-22 17:53:13.238352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37ffb990dd9d'
down_revision: Union[str, None] = 'a38a713ed79e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('files_file_text_id_key', 'files', type_='unique')
    op.drop_constraint('files_file_text_id_fkey', 'files', type_='foreignkey')
    op.drop_column('files', 'file_text_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_text_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('files_file_text_id_fkey', 'files', 'file_text', ['file_text_id'], ['id'])
    op.create_unique_constraint('files_file_text_id_key', 'files', ['file_text_id'])
    # ### end Alembic commands ###
