"""drop_file_text

Revision ID: 4e3a04b183d9
Revises: 37ffb990dd9d
Create Date: 2024-06-22 21:27:01.625128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e3a04b183d9'
down_revision: Union[str, None] = '37ffb990dd9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_text', 'search_vector',
               existing_type=postgresql.TSVECTOR(),
               nullable=False)
    op.drop_column('file_text', 'file_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_text', sa.Column('file_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('file_text', 'search_vector',
               existing_type=postgresql.TSVECTOR(),
               nullable=True)
    # ### end Alembic commands ###
