"""add file_text

Revision ID: ab8d38529f87
Revises: 4e3a04b183d9
Create Date: 2024-06-22 21:27:54.352323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab8d38529f87'
down_revision: Union[str, None] = '4e3a04b183d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_text', sa.Column('file_text', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_text', 'file_text')
    # ### end Alembic commands ###
