"""add_user_id_column

Revision ID: fe8bdc885752
Revises: ab8d38529f87
Create Date: 2024-06-22 22:21:10.467725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8bdc885752'
down_revision: Union[str, None] = 'ab8d38529f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_text', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_file_text_user_id'), 'file_text', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_text_user_id'), table_name='file_text')
    op.drop_column('file_text', 'user_id')
    # ### end Alembic commands ###
