"""Add Language Column

Revision ID: b5322b8ce4e7
Revises: fe8bdc885752
Create Date: 2024-09-22 09:57:57.157172

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b5322b8ce4e7"
down_revision: Union[str, None] = "fe8bdc885752"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files",
        sa.Column("language", sa.String(length=2), nullable=False, server_default="en"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "language")
    # ### end Alembic commands ###
