"""add language column

Revision ID: 19844bf5e9e2
Revises: b5322b8ce4e7
Create Date: 2024-09-26 19:55:27.110834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19844bf5e9e2'
down_revision: Union[str, None] = 'b5322b8ce4e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_text', sa.Column('file_language', sa.String(length=31), server_default='english', nullable=False))
    op.alter_column('file_text', 'file_text',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.ARRAY(sa.Text()),
               existing_nullable=True)
    op.drop_column('files', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('language', sa.VARCHAR(length=2), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=False))
    op.alter_column('file_text', 'file_text',
               existing_type=sa.ARRAY(sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.drop_column('file_text', 'file_language')
    # ### end Alembic commands ###
