"""make search_vector nullable

Revision ID: 5d08e9fe5d38
Revises: 19844bf5e9e2
Create Date: 2024-09-26 20:41:46.881348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d08e9fe5d38'
down_revision: Union[str, None] = '19844bf5e9e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_text', 'search_vector',
               existing_type=postgresql.TSVECTOR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_text', 'search_vector',
               existing_type=postgresql.TSVECTOR(),
               nullable=False)
    # ### end Alembic commands ###
