FROM ubuntu:20.04 as base-image
ENV PYTHONUNBUFFERED=1
ARG DEBIAN_FRONTEND=noninteractive

RUN apt update -y && apt upgrade -y

RUN apt install -y make git build-essential libssl-dev zlib1g-dev \
    libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
    libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev


ENV HOME="/root"
WORKDIR ${HOME}
RUN apt-get install -y git
RUN git clone --depth=1 https://github.com/pyenv/pyenv.git .pyenv
ENV PYENV_ROOT="${HOME}/.pyenv"
ENV PATH="${PYENV_ROOT}/shims:${PYENV_ROOT}/bin:${PATH}"


RUN pyenv install 3.12.3
RUN pyenv global 3.12.3

RUN mkdir /app
RUN mkdir /venv
RUN mkdir /app/logs

RUN apt install gunicorn -y
WORKDIR /app


FROM base-image as venv-image
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update -y && apt upgrade -y

RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

RUN pip3 install --upgrade pip
RUN pip3 install gunicorn

COPY requirements.txt .
RUN pip3 install -r requirements.txt


FROM base-image

COPY --from=venv-image /venv /venv
ENV VIRTUAL_ENV=/venv
ENV PATH="/venv/bin:$PATH"

COPY . /app
RUN mv /app/docker/start.sh /start.sh
RUN chmod +x /start.sh
EXPOSE 8080

CMD ["/bin/bash", "/start.sh"]
 